[package]
name = "lox"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
thiserror = "2.0.12"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = 'abort'
strip = true
